services: 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: always

  backend:
    build: ./backend
    expose:
      - "8080"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      target: build
    volumes:
      - ./frontend:/app
    restart: always 
