services:
  backend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: sh -c "npx nodemon server.js"

  frontend:
    build:
      context: ./frontend
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
